export type Opportunity = {
  id: string;
  title: string;
  company: string;
  industry: string;
  town: string;
  county: string;
  duration: string;
  startDate: string;
  endDate: string;
  availableSlots: number;
  eligibleCourses: string[];
  paid: boolean;
  accommodation: boolean;
  reservationFee: number;
  applicationDeadline: string;
  verified: boolean;
  demo: boolean;
};

export const opportunities: Opportunity[] = [
  {
    id: "opp-001",
    title: "Software Engineering Attachment",
    company: "Demo Technology Solutions",
    industry: "Technology",
    town: "Nairobi",
    county: "Nairobi",
    duration: "3 months",
    startDate: "2027-01-05",
    endDate: "2027-04-05",
    availableSlots: 4,
    eligibleCourses: ["Computer Science", "Software Engineering", "IT"],
    paid: false,
    accommodation: false,
    reservationFee: 1500,
    applicationDeadline: "2026-12-15",
    verified: true,
    demo: true,
  },
  {
    id: "opp-002",
    title: "ICT Support Attachment",
    company: "Sample Digital Services",
    industry: "Technology",
    town: "Nakuru",
    county: "Nakuru",
    duration: "3 months",
    startDate: "2027-01-12",
    endDate: "2027-04-12",
    availableSlots: 6,
    eligibleCourses: ["Information Technology", "Computer Science"],
    paid: false,
    accommodation: false,
    reservationFee: 1200,
    applicationDeadline: "2026-12-20",
    verified: true,
    demo: true,
  },
  {
    id: "opp-003",
    title: "Agribusiness Operations Attachment",
    company: "Sample Rift Valley Agritech",
    industry: "Agriculture",
    town: "Naivasha",
    county: "Nakuru",
    duration: "4 months",
    startDate: "2027-01-06",
    endDate: "2027-05-06",
    availableSlots: 3,
    eligibleCourses: ["Agriculture", "Business Administration"],
    paid: true,
    accommodation: true,
    reservationFee: 2000,
    applicationDeadline: "2026-12-10",
    verified: true,
    demo: true,
  },
  {
    id: "opp-004",
    title: "Finance and Accounting Attachment",
    company: "Sample Nakuru Business Services",
    industry: "Finance",
    town: "Nakuru",
    county: "Nakuru",
    duration: "3 months",
    startDate: "2027-01-18",
    endDate: "2027-04-18",
    availableSlots: 5,
    eligibleCourses: ["Finance", "Accounting"],
    paid: false,
    accommodation: false,
    reservationFee: 1500,
    applicationDeadline: "2026-12-22",
    verified: false,
    demo: true,
  },
  {
    id: "opp-005",
    title: "Hospitality Operations Attachment",
    company: "Demo Naivasha Hospitality Group",
    industry: "Hospitality",
    town: "Naivasha",
    county: "Nakuru",
    duration: "4 months",
    startDate: "2027-01-04",
    endDate: "2027-05-04",
    availableSlots: 8,
    eligibleCourses: ["Hospitality"],
    paid: true,
    accommodation: true,
    reservationFee: 1800,
    applicationDeadline: "2026-12-08",
    verified: true,
    demo: true,
  },
  {
    id: "opp-006",
    title: "Human Resource Management Attachment",
    company: "Demo Corporate Services",
    industry: "Business",
    town: "Nairobi",
    county: "Nairobi",
    duration: "3 months",
    startDate: "2027-01-11",
    endDate: "2027-04-11",
    availableSlots: 2,
    eligibleCourses: ["Human Resource Management", "Business Administration"],
    paid: false,
    accommodation: false,
    reservationFee: 1300,
    applicationDeadline: "2026-12-18",
    verified: true,
    demo: true,
  },
  {
    id: "opp-007",
    title: "Logistics and Supply Chain Attachment",
    company: "Demo Logistics Kenya",
    industry: "Logistics",
    town: "Naivasha",
    county: "Nakuru",
    duration: "3 months",
    startDate: "2027-01-08",
    endDate: "2027-04-08",
    availableSlots: 7,
    eligibleCourses: ["Supply Chain and Logistics", "Business Administration"],
    paid: false,
    accommodation: false,
    reservationFee: 1500,
    applicationDeadline: "2026-12-14",
    verified: true,
    demo: true,
  },
  {
    id: "opp-008",
    title: "Environmental Science Attachment",
    company: "Sample Green Solutions",
    industry: "Environment",
    town: "Nakuru",
    county: "Nakuru",
    duration: "4 months",
    startDate: "2027-01-15",
    endDate: "2027-05-15",
    availableSlots: 3,
    eligibleCourses: ["Environmental Science"],
    paid: false,
    accommodation: true,
    reservationFee: 1700,
    applicationDeadline: "2026-12-16",
    verified: true,
    demo: true,
  },
  {
    id: "opp-009",
    title: "Software Development Attachment",
    company: "Demo Digital Labs",
    industry: "Technology",
    town: "Nairobi",
    county: "Nairobi",
    duration: "4 months",
    startDate: "2027-02-01",
    endDate: "2027-06-01",
    availableSlots: 5,
    eligibleCourses: ["Software Engineering", "Computer Science"],
    paid: true,
    accommodation: false,
    reservationFee: 2000,
    applicationDeadline: "2027-01-05",
    verified: true,
    demo: true,
  },
  {
    id: "opp-010",
    title: "Marketing Attachment",
    company: "Sample Growth Agency",
    industry: "Marketing",
    town: "Nairobi",
    county: "Nairobi",
    duration: "3 months",
    startDate: "2027-01-20",
    endDate: "2027-04-20",
    availableSlots: 4,
    eligibleCourses: ["Marketing", "Business Administration"],
    paid: false,
    accommodation: false,
    reservationFee: 1200,
    applicationDeadline: "2026-12-20",
    verified: false,
    demo: true,
  },
  {
    id: "opp-011",
    title: "Engineering Attachment",
    company: "Demo Industrial Works",
    industry: "Engineering",
    town: "Nakuru",
    county: "Nakuru",
    duration: "4 months",
    startDate: "2027-01-10",
    endDate: "2027-05-10",
    availableSlots: 2,
    eligibleCourses: ["Engineering"],
    paid: false,
    accommodation: false,
    reservationFee: 1800,
    applicationDeadline: "2026-12-12",
    verified: true,
    demo: true,
  },
  {
    id: "opp-012",
    title: "Business Administration Attachment",
    company: "Sample Business Hub",
    industry: "Business",
    town: "Naivasha",
    county: "Nakuru",
    duration: "3 months",
    startDate: "2027-01-17",
    endDate: "2027-04-17",
    availableSlots: 6,
    eligibleCourses: ["Business Administration", "Human Resource Management"],
    paid: false,
    accommodation: true,
    reservationFee: 1300,
    applicationDeadline: "2026-12-17",
    verified: false,
    demo: true,
  },
];
